version: '3.8'

services:
  piwigo1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piwigo1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./shared_gallery:/gallery
      - ./Images:/initial_images
    ports:
      - "81:80"
    networks:
      - piwigo-net
    restart: unless-stopped

  piwigo2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piwigo2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./shared_gallery:/gallery
      - ./Images:/initial_images
    ports:
      - "82:80"
    networks:
      - piwigo-net
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=piwigo_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mariadb_data:/config
    networks:
      - piwigo-net
    restart: unless-stopped

networks:
  piwigo-net:
    driver: bridge
